# Generated by Django 2.1.1 on 2018-09-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180926_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='units',
            field=models.CharField(choices=[('km', 'kilometers'), ('miles', 'miles')], default='km', max_length=5),
        ),
        migrations.AlterField(
            model_name='run',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
