# Generated by Django 2.1.1 on 2018-09-27 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180926_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
